<a href="https://colab.research.google.com/github/MuskanBansal2001/MB_Explanatory_Analysis_ybi/blob/main/Boston_Housing_Prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#step 1: Import Library
import pandas as pd

In [2]:
#step 2: Import dataset
data = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Boston.csv')

In [3]:
data.head()

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [4]:
data.tail()

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [5]:
#Understanding dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NX       506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [6]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [7]:
#step 3: define target(y) and features(x)
data.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [8]:
x = data[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX','PTRATIO', 'B', 'LSTAT']]
y = data['MEDV']

In [9]:
#step 4: splitting of data for training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,random_state=2529)

In [10]:
#step 5: Selection of model, going into predictive modeling ie using experience to predict
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [11]:
#step 6: train the model aka fit model
# this is the step where ML happens, before we were just making the dataset ready
model.fit(x_train, y_train)
# .fit is the function used for training

LinearRegression()

In [12]:
model.intercept_
#will give c

31.25533453751924

In [13]:
model.coef_
#will give slope ie m

array([-1.27113473e-01,  3.42913377e-02,  2.60868350e-03,  2.38959719e+00,
       -1.82552392e+01,  4.48454125e+00,  1.61769130e-03, -1.46612188e+00,
        2.40205715e-01, -9.08110896e-03, -9.17943140e-01,  1.03133823e-02,
       -5.29465536e-01])

In [14]:
#step 7: is about prediction
y_pred = model.predict(x_test)
y_pred

array([31.57707257, 21.99233175, 21.04895711, 39.65540204, 20.24464386,
       22.4734502 , 18.43113851, 14.97297011, 22.72405304, 21.46176742,
       18.41749475, 28.0052573 , 29.54086585,  6.26556553, 10.85497948,
       26.24298198, 21.86003365, 25.17832317,  3.67994913, 36.19092657,
       24.13675718, 23.14472095, 14.35696101, 20.76855022, 24.52207463,
       17.1623051 , 18.87496554, 21.21502722, 28.5169502 , 20.83879317,
        8.80754651, 17.22509292, 22.24432694, 22.31154655, 39.00283202,
       26.11363885, 42.15325106, 19.65839754, 34.01336499, 14.10243751,
       13.92013551, 23.05184377, 12.00029947,  8.96217254, 21.77793634,
       25.34289659, 18.32959331, 17.00193196, 14.58219552, 15.29442317,
       33.53996827, 33.17641753, 15.66181428, 23.95055159, 27.48247864,
       19.57803692, 44.77479846, 20.78150726, 20.22559656, 27.6863577 ,
       34.41715912, 12.75996249, 23.60283934, 31.67489274, 28.71125633,
       32.2039887 , 13.69571608, 35.28183162, 19.52594181, 19.3570412 ,
        1.50116192, 23.95490742, 33.69298981, 20.80716313, 26.59638606,
       21.56598182, 31.74682671, 29.17279713, 14.05122178, 13.80568897,
       19.6992601 , 21.58810664, 20.83952316, 23.50032757, 28.66348398,
       23.50871961,  7.0746767 , 22.06999562, -6.66179307, 17.08629723,
       16.77473684, 25.23910113, 15.07894744,  4.01688714, 14.95820229,
       16.69469222, 21.8201562 , 31.60755266, 30.61568681, 24.17187818,
       22.38536675, 13.81004779, 18.54801917, 18.25659609, 36.28662163,
       27.50624293, 11.17365829, 17.46850162, 22.12645376, 16.45372163,
       29.31179722, 22.80625661, 24.26074845, 20.69296826, 19.86805259,
       23.09549258, 27.43051376, 25.12139159, 20.13814047, 28.96623349,
        7.66128334,  6.03380199, 25.38323135, 38.88931995, 23.78082623,
       25.28177288, 20.2228091 ])

In [15]:
x_test

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
229,0.44178,0.0,6.20,0,0.504,6.552,21.4,3.3751,8,307.0,17.4,380.34,3.76
45,0.17142,0.0,6.91,0,0.448,5.682,33.8,5.1004,3,233.0,17.9,396.90,10.21
119,0.14476,0.0,10.01,0,0.547,5.731,65.2,2.7592,6,432.0,17.8,391.50,13.61
232,0.57529,0.0,6.20,0,0.507,8.337,73.3,3.8384,8,307.0,17.4,385.91,2.47
461,3.69311,0.0,18.10,0,0.713,6.376,88.4,2.5671,24,666.0,20.2,391.43,14.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,0.16760,0.0,7.38,0,0.493,6.426,52.3,4.5404,5,287.0,19.6,396.90,7.20
364,3.47428,0.0,18.10,1,0.718,8.780,82.9,1.9047,24,666.0,20.2,354.55,5.29
309,0.34940,0.0,9.90,0,0.544,5.972,76.7,3.1025,4,304.0,18.4,396.24,9.97
84,0.05059,0.0,4.49,0,0.449,6.389,48.0,4.7794,3,247.0,18.5,396.90,9.62
464,7.83932,0.0,18.10,0,0.655,6.209,65.4,2.9634,24,666.0,20.2,396.90,13.22

In [16]:
#step 8: is the accuracy of the model
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

0.1702803409644982